AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BaseName:
    Type: String
    Description: Project Base Name - Used to assign names across resources
  StageName:
    Type: String
    Description: Project Stage Name - Used to separate resources in different stages
  HostedZoneId:
    Type: String
  HostedZoneDomain:
    Type: String
  DBMasterUsername:
    Type: String
  DBMasterPassword:
    Type: String

Resources:
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BaseName}-${StageName}-${AWS::Region}-content
      VersioningConfiguration:
        Status: Enabled

  CoverBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BaseName}-${StageName}-${AWS::Region}-cover
      VersioningConfiguration:
        Status: Enabled

  AvatarBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BaseName}-${StageName}-${AWS::Region}-avatar
      VersioningConfiguration:
        Status: Enabled

#  RecordSet:
#    Type: AWS::Route53::RecordSet
#    Properties:
#      HostedZoneId: !Ref HostedZoneId
#      Name: !Sub ${StageName}-storage.${HostedZoneDomain}
#      ResourceRecords:
#        - !GetAtt DBInstance.Endpoint.Address
#      TTL: '60'
#      Type: CNAME
#
#  DBInstance:
#    DeletionPolicy: Snapshot
#    UpdateReplacePolicy: Snapshot
#    Type: AWS::RDS::DBInstance
#    Properties:
#      AllocatedStorage: 20
#      BackupRetentionPeriod: 7
#      DBInstanceClass: db.t2.micro
#      DBName: !Sub ${BaseName}${StageName}db
#      DBInstanceIdentifier: !Sub ${BaseName}-${StageName}-instance
#      Engine: postgres
#      MasterUsername: !Ref DBMasterUsername
#      MasterUserPassword: !Ref DBMasterPassword
